### ISSUE TITLE
question: what is the correct expected value in the *_TEST.java files?

### ISSUE THREAD

**Issue by monperrus** [jkoppel/QuixBugs#1]
I'm looking at the *_TEST.java files. Since they don't contain assertions, it is unclear what the correct expected value is. Is it the one with `output:` in comment?

**Comment by drrckln** [comment]
Yes, that's correct. The comment is for convenience and not the reference expected value, though; that would simply be the output of the correct implementation. The included test driver runs all versions of a given program (including the correct implementation), and prints the outputs for visual comparison. I hope that helps.

**Comment by monperrus** [comment]
Thanks for your answer.

Beyond visual comparison, is there an automated test driver that can be 
used for driving a program repair tool?

**Comment by drrckln** [comment]
Not currently. We already know that the testcase implementation needs some reworking, and any other thoughts for making the set more useful would be welcomed. So thanks for your (implicit) suggestion!

**Comment by jkoppel** [comment]
We're not exactly sure what you mean by test driver. Are you asking if there's a shell script ./foo such that "./foo myprogram" will run myprogram on every test?

**Comment by monperrus** [comment]
By test driver, I mean something that runs all tests for a given task, with some API to get the
number of failed and passed tests.

If we translate the current tests into Junit tests, Junit would be the test driver.

**Comment by jkoppel** [comment]
No, there is no such driver. I don't see a good way to write such a driver in a manner that it can be easily incorporated into any program repair tool.

**Comment by monperrus** [comment]
Translating the current tests as Junit tests is an option.

Since the tests seem to follow a convention, the translation can probably automated with a
source-to-source transformation library such as Spoon <https://github.com/INRIA/spoon/>.

**Comment by jkoppel** [comment]
Oh wait, are you referring to running the transformed programs, rather than running the program repair tool?

**Comment by monperrus** [comment]
I mean running the program repair tool on the Java programs of QuixBugs.

**Comment by jkoppel** [comment]
Okay. We're still having trouble understanding what you want. What would a
driver look like that could run both our tool the Quixey Challenger
(written in Haskell) and GenProg for Java (written in Java) on the Java
examples?

**Comment by monperrus** [comment]
Interesting, how did you run GenProg for Java on the Java examples?

**Comment by jkoppel** [comment]
We didn't; we only ran the Quixey Challenger.

**Comment by jkoppel** [comment]
So, in short: If there's a case for why most program repair tools would use the same driver, then it makes sense for us to provide such a driver.  If there's not, then it makes sense for each tool to have their own shell script. We're open to other ideas about how to make this benchmark set easier to use.

**Comment by monperrus** [comment]
> most program repair tools would use the same driver, then it makes 
> sense for us to provide such a driver
To my knowledge, most program repair tools assume a Junit test suite 
with Junit assertions encoding the expected behavior. So it would be 
great to have such Junit tests directly in the repo.

**Comment by jkoppel** [comment]
Hmmm....really? Can you give some examples?

I just had a look at the first 7 tools linked to from http://program-repair.org/tools.html (note that the "Kali" link actually links to 3 tools). Of those, only one, Genesis, used JUnit, and it only used it to test some of its internal functionality, not to run Genesis on other programs. I then realized I had been looking under the "C/C++" section, so I then looked at the first 3 tools in the "Java" section not written by you that I could get the source code for. ACS and NPEFix both use JUnit, but it looks like ACS only uses it to test internal functionality. NPEFix does use JUnit to do an end-to-end test of the patcher on an example ( https://github.com/Spirals-Team/npefix/blob/master/src/test/java/fr/inria/spirals/npefix/patch/PatchesGeneratorTest.java ), but the test is written in a very non-portable fashion.

So, of 10 tools, only one of them uses JUnit in the way that I understand you to be requesting, and it does so in a fashion that's not portable to other tools.

So, I really don't know what you're asking for.

Martin, what is your end goal? Are you trying to run one of your tools on the Java benchmarks? Are you having trouble doing that?

**Comment by monperrus** [comment]
> Are you trying to run one of your tools on the Java benchmarks?
yes
> Are you having trouble doing that?
It's impossible out-of-the-box without having the *_TEST.java files written as Junit tests with
expected behavior as Junit assertions (and not as comment).

**Comment by drrckln** [comment]
For now, a majority of the programs have testcases (input/output pairs) written in JSON. There's a deserializer (JSON -> Java) in the root directory that could be adapted. The benchmark wasn't written to be used this way; you might have noticed that there's only about ten "*_TEST.java" files. We presumed that input/output pairs would be deserialized into the target language (by a tool similar to our test driver) and that the program repair tool could take it from there.

I think I understand your request, but could you supply an example of a JUnit test in the form you're looking for?

**Comment by monperrus** [comment]
> For now, a majority of the programs have testcases (input/output pairs) written in JSON.

That's a key information, thanks! 

So the answer to this question is:

1. for the 8 programs with `*_TEST.java`, those `*_TEST.java` are not Junit test cases, but could be rewritten as such, the expected value is written as comment
2. for 31 programs, the test data is provided as json, and it is possible to generate Junit test classes from the JSON files, see #2.
 
I'm closing this thread.
