### ISSUE TITLE
Adding passing test cases

### ISSUE THREAD

**Issue by agb94** [jkoppel/QuixBugs#32]
Hi, 

I’m a master student at COINSE, KAIST and developing a Genetic Improvement framework called PyGGI.

First of all, thanks for providing a multi-lingual program benchmark.

I am currently running an APR experiment on this benchmark and found that there are some faulty programs that have no passing test at all (ex. mergesort, bucketsort, shunting_yard, …). This makes it difficult to distinguish the original faulty program from even worse programs. 

So, I've created several passing test cases for some of those programs by automatically generating inputs that satisfy the described input precondition and yield the same output on both correct and faulty program. To do so, I repeatedly mutated the original failing test inputs until finding such test inputs.

If you think this may help, I'd like to open a pull request which will add passing test inputs to the existing JSON files. Thank you!

**Comment by monperrus** [comment]
> I am currently running an APR experiment on this benchmark and found that there are some faulty
> programs that have no passing test at all (ex. mergesort, bucketsort, shunting_yard, …). This
> makes it difficult to distinguish the original faulty program from even worse programs.
>
FYI, @sophiehye was able to find patches, incl. correct patches, only with the failing test cases,
see http://arxiv.org/pdf/1805.03454

**Comment by jkoppel** [comment]
Thanks for the offer.

@drrckln, I'm calling Chesterton's Fence. Are these programs indeed lacking passing test cases, and if so is there a reason for this?

**Comment by drrckln** [comment]
Yes, they're lacking -- we wrote passing test cases where we could find one (by hand, using our understanding of each program's bug), but several programs are faulty enough that they appeared to never give correct output. So we left those.

However, we didn't use generated tests to search the space. So I could totally believe something like QuickCheck would find some passing tests. My understanding is that most tests are still written by hand, so I am unsure of the value of the passing test cases -- not having any is an additional challenge that seems to be surmountable, as apparently @SophieHYe has shown.

**Comment by jkoppel** [comment]
I approve of adding passing test cases if you can find any.

I'd prefer human-written over auto-generated tests though for two reasons. First, they're likely to be more comprehensible. Second, if you can find auto-generated passing tests, but you can't construct any by hand, then something is fishy.

**Comment by ntrolls** [comment]
For context, I'm the supervisor of both COINSE lab and @agb94.

@monperrus Yes, and I believe @agb94 has a similar result, but we thought it may be nicer to have them anyway... :)
@jkoppel Thanks for the Chesterton reference! I believe @agb94 's decision to automate the process was simply to do with time saving. We will try to manually confirm them if we eventually do send a PR.

**Comment by agb94** [comment]
@jkoppel

I've reviewed the generated passing test cases and uploaded some of them to my repository. please review this commit and tell me what should be selected or removed: https://github.com/agb94/QuixBugs/commit/69cbd14458a8bfe83141497c982344653141a8a0

The new passing tests of `lis` and `to_base` look more general and reasonable, while other passing test cases are close to the edge cases (but I think it would be nicer if a test suite contains edge cases). FYI, the selected passing tests were able to detect at least one version of mutated programs with line- or statement-level edit operators. And each of new test cases for `lis` and `to_base` could detect different sets of program mutants. (grouped test cases: https://www.dropbox.com/s/mg1lw0v7c4owj8v/passing_lis_correct.txt?dl=0, https://www.dropbox.com/s/w3zwtybpn518uqe/passing_to_base_correct.txt?dl=0)

**Comment by jkoppel** [comment]
I approve of all the test cases added in commit 69cbd14458a8bfe83141497c982344653141a8a0

**Comment by agb94** [comment]
Ok, I've sent a PR :)

https://github.com/jkoppel/QuixBugs/pull/33
