### ISSUE TITLE
License/Can I modify reuse this for research?

### ISSUE THREAD

**Issue by PatrickShaw** [jkoppel/QuixBugs#34]
Hi, since there's no explicit licensing on the repository, I wanted to clarify if I'm permitted to modify (create a JavaScript version of the programs) and use it for my own purposes (my honours project).

I'm assuming the answer is rest, but I figured I'd ask to be sure - You never know :)

**Comment by jkoppel** [comment]
Hello Patrick,

I've just put this under the MIT license, so yes you may. If your translations are god, please contribute them back.

**Comment by PatrickShaw** [comment]
No worries, thanks very much!
