### ISSUE TITLE
suggestion: activate Travis CI?

### ISSUE THREAD

**Issue by monperrus** [jkoppel/QuixBugs#5]
Hi, I've prepared a gradle build file that is compatible with Travis. It would ensure that everything compiles.

I'll create a pull request once the compilation errors are fixed in #1.

Could you activate Travis on this repo?

**Comment by jkoppel** [comment]
https://travis-ci.org/jkoppel/QuixBugs

**Comment by monperrus** [comment]
Perfect, welcome CI: #6
